variables:

# =========================================================
# ENVIRONMENT
# =========================================================

- name: EnvironmentName
  value: 'Production'

# =========================================================
# SQL
# =========================================================

- name: SqlServer
  value: 'PRODSQL'

# =========================================================
# TEAMS
# =========================================================

- name: TeamsWebhookUrl
  value: 'https://prod-webhook-url'

# =========================================================
# DOMAIN
# =========================================================

- name: BaseDomain
  value: 'company.com'