trigger: none
pr: none
name: '1.0.$(Rev:r)'
lockBehavior: sequential
pool:
  name: 'SelfHosted-Windows-Agent'

# =========================================================
# PARAMETERS
# =========================================================

parameters:

# =========================================================
# MICROSERVICE SELECTION
# =========================================================

- name: serviceName

  displayName: 'Select Microservice'

  type: string

  default: 'claimservice'

  values:
    - claimservice
    - authservice
    - paymentservice

# =========================================================
# ENVIRONMENT SELECTION
# =========================================================

- name: environmentName

  displayName: 'Select Environment'

  type: string

  default: 'dev'

  values:
    - dev
    - qa
    - uat
    - staging
    - prod

variables:
# GLOBAL VARIABLES
- template: Deployements/ci-cd/pipelines/variables/global.yml

# ENVIRONMENT VARIABLES
- template: Deployments/ci-cd/pipelines/environments/${{ parameters.environmentName }}.yml

# SERVICE VARIABLES
- template: Deployments/ci-cd/pipelines/services/${{ parameters.serviceName }}.yml

# =========================================================
# STAGES
# =========================================================
stages:

# BUILD
- template: Deployments/ci-cd/pipelines/templates/build.yml

# DEPLOY
- template: Deployments/ci-cd/pipelines/templates/deploy.yml